
export const topSites = [
    { name: 'Google', domain: 'google.com', url: 'https://google.com', category: 'Search Engine', rank: 1 },
    { name: 'YouTube', domain: 'youtube.com', url: 'https://youtube.com', category: 'Video', rank: 2 },
    { name: 'Facebook', domain: 'facebook.com', url: 'https://facebook.com', category: 'Social Media', rank: 3 },
    { name: 'X (Twitter)', domain: 'x.com', url: 'https://x.com', category: 'Social Media', rank: 4 },
    { name: 'Instagram', domain: 'instagram.com', url: 'https://instagram.com', category: 'Social Media', rank: 5 },
    { name: 'Wikipedia', domain: 'wikipedia.org', url: 'https://wikipedia.org', category: 'Reference', rank: 6 },
    { name: 'Amazon', domain: 'amazon.com', url: 'https://amazon.com', category: 'E-commerce', rank: 7 },
    { name: 'Netflix', domain: 'netflix.com', url: 'https://netflix.com', category: 'Streaming', rank: 8 },
    { name: 'Reddit', domain: 'reddit.com', url: 'https://reddit.com', category: 'Social Media', rank: 9 },
    { name: 'LinkedIn', domain: 'linkedin.com', url: 'https://linkedin.com', category: 'Professional', rank: 10 },
    { name: 'The New York Times', domain: 'nytimes.com', url: 'https://www.nytimes.com', category: 'News', rank: 11 },
    { name: 'BBC', domain: 'bbc.com', url: 'https://www.bbc.com', category: 'News', rank: 12 },
    { name: 'Microsoft', domain: 'microsoft.com', url: 'https://microsoft.com', category: 'Technology', rank: 13 },
    { name: 'Apple', domain: 'apple.com', url: 'https://apple.com', category: 'Technology', rank: 14 },
    { name: 'GitHub', domain: 'github.com', url: 'https://github.com', category: 'Developer', rank: 15 },
    { name: 'Stack Overflow', domain: 'stackoverflow.com', url: 'https://stackoverflow.com', category: 'Developer', rank: 16 },
    { name: 'Vercel', domain: 'vercel.com', url: 'https://vercel.com', category: 'Developer', rank: 17 },
    { name: 'Figma', domain: 'figma.com', url: 'https://figma.com', category: 'Design', rank: 18 },
    { name: 'Canva', domain: 'canva.com', url: 'https://canva.com', category: 'Design', rank: 19 },
    { name: 'Spotify', domain: 'spotify.com', url: 'https://spotify.com', category: 'Music', rank: 20 },
    { name: 'TikTok', domain: 'tiktok.com', url: 'https://tiktok.com', category: 'Social Media', rank: 21 },
    { name: 'Pinterest', domain: 'pinterest.com', url: 'https://pinterest.com', category: 'Social Media', rank: 22 },
    { name: 'eBay', domain: 'ebay.com', url: 'https://ebay.com', category: 'E-commerce', rank: 23 },
    { name: 'Walmart', domain: 'walmart.com', url: 'https://walmart.com', category: 'E-commerce', rank: 24 },
    { name: 'Target', domain: 'target.com', url: 'https://target.com', category: 'E-commerce', rank: 25 },
    { name: 'The Guardian', domain: 'theguardian.com', url: 'https://theguardian.com/international', category: 'News', rank: 26 },
    { name: 'CNN', domain: 'cnn.com', url: 'https://cnn.com', category: 'News', rank: 27 },
    { name: 'Forbes', domain: 'forbes.com', url: 'https://forbes.com', category: 'Business', rank: 28 },
    { name: 'ESPN', domain: 'espn.com', url: 'https://espn.com', category: 'Sports', rank: 29 },
    { name: 'IMDb', domain: 'imdb.com', url: 'https://imdb.com', category: 'Entertainment', rank: 30 },
    { name: 'Twitch', domain: 'twitch.tv', url: 'https://twitch.tv', category: 'Streaming', rank: 31 },
    { name: 'Adobe', domain: 'adobe.com', url: 'https://adobe.com', category: 'Software', rank: 32 },
    { name: 'Salesforce', domain: 'salesforce.com', url: 'https://salesforce.com', category: 'Business', rank: 33 },
    { name: 'PayPal', domain: 'paypal.com', url: 'https://paypal.com', category: 'Finance', rank: 34 },
    { name: 'Dropbox', domain: 'dropbox.com', url: 'https://dropbox.com', category: 'Cloud Storage', rank: 35 },
    { name: 'Slack', domain: 'slack.com', url: 'https://slack.com', category: 'Productivity', rank: 36 },
    { name: 'Zoom', domain: 'zoom.us', url: 'https://zoom.us', category: 'Productivity', rank: 37 },
    { name: 'Quora', domain: 'quora.com', url: 'https://quora.com', category: 'Q&A', rank: 38 },
    { name: 'Medium', domain: 'medium.com', url: 'https://medium.com', category: 'Blogging', rank: 39 },
    { name: 'Booking.com', domain: 'booking.com', url: 'https://booking.com', category: 'Travel', rank: 40 },
    { name: 'Airbnb', domain: 'airbnb.com', url: 'https://airbnb.com', category: 'Travel', rank: 41 },
    { name: 'Uber', domain: 'uber.com', url: 'https://uber.com', category: 'Transportation', rank: 42 },
    { name: 'Lyft', domain: 'lyft.com', url: 'https://lyft.com', category: 'Transportation', rank: 43 },
    { name: 'DoorDash', domain: 'doordash.com', url: 'https://doordash.com', category: 'Food Delivery', rank: 44 },
    { name: 'Etsy', domain: 'etsy.com', url: 'https://etsy.com', category: 'E-commerce', rank: 45 },
    { name: 'Shopify', domain: 'shopify.com', url: 'https://shopify.com', category: 'E-commerce', rank: 46 },
    { name: 'WordPress.org', domain: 'wordpress.org', url: 'https://wordpress.org', category: 'CMS', rank: 47 },
    { name: 'Wix', domain: 'wix.com', url: 'https://wix.com', category: 'Website Builder', rank: 48 },
    { name: 'Squarespace', domain: 'squarespace.com', url: 'https://squarespace.com', category: 'Website Builder', rank: 49 },
    { name: 'The Verge', domain: 'theverge.com', url: 'https://theverge.com', category: 'Tech News', rank: 50 },
    { name: 'TechCrunch', domain: 'techcrunch.com', url: 'https://techcrunch.com', category: 'Tech News', rank: 51 },
    { name: 'Hacker News', domain: 'ycombinator.com', url: 'https://news.ycombinator.com', category: 'Tech News', rank: 52 },
    { name: 'National Geographic', domain: 'nationalgeographic.com', url: 'https://nationalgeographic.com', category: 'Education', rank: 53 },
    { name: 'NASA', domain: 'nasa.gov', url: 'https://nasa.gov', category: 'Science', rank: 54 },
    { name: 'WebMD', domain: 'webmd.com', url: 'https://webmd.com', category: 'Health', rank: 55 },
    { name: 'Healthline', domain: 'healthline.com', url: 'https://healthline.com', category: 'Health', rank: 56 },
    { name: 'Allrecipes', domain: 'allrecipes.com', url: 'https://allrecipes.com', category: 'Food', rank: 57 },
    { name: 'Food Network', domain: 'foodnetwork.com', url: 'https://foodnetwork.com', category: 'Food', rank: 58 },
    { name: 'IGN', domain: 'ign.com', url: 'https://ign.com', category: 'Gaming', rank: 59 },
    { name: 'GameSpot', domain: 'gamespot.com', url: 'https://gamespot.com', category: 'Gaming', rank: 60 },
    { name: 'Rotten Tomatoes', domain: 'rottentomatoes.com', url: 'https://rottentomatoes.com', category: 'Entertainment', rank: 61 },
    { name: 'SoundCloud', domain: 'soundcloud.com', url: 'https://soundcloud.com', category: 'Music', rank: 62 },
    { name: 'Bandcamp', domain: 'bandcamp.com', url: 'https://bandcamp.com', category: 'Music', rank: 63 },
    { name: 'DeviantArt', domain: 'deviantart.com', url: 'https://deviantart.com', category: 'Art', rank: 64 },
    { name: 'Behance', domain: 'behance.net', url: 'https://behance.net', category: 'Design', rank: 65 },
    { name: 'Dribbble', domain: 'dribbble.com', url: 'https://dribbble.com', category: 'Design', rank: 66 },
    { name: 'Alibaba', domain: 'alibaba.com', url: 'https://alibaba.com', category: 'E-commerce', rank: 67 },
    { name: 'Tencent', domain: 'tencent.com', url: 'https://tencent.com', category: 'Technology', rank: 68 },
    { name: 'Baidu', domain: 'baidu.com', url: 'https://baidu.com', category: 'Search Engine', rank: 69 },
    { name: 'Yahoo', domain: 'yahoo.com', url: 'https://yahoo.com', category: 'Portal', rank: 70 },
    { name: 'WhatsApp', domain: 'whatsapp.com', url: 'https://whatsapp.com', category: 'Social Media', rank: 71 },
    { name: 'Telegram', domain: 'telegram.org', url: 'https://telegram.org', category: 'Social Media', rank: 72 },
    { name: 'Discord', domain: 'discord.com', url: 'https://discord.com', category: 'Social Media', rank: 73 },
    { name: 'Vimeo', domain: 'vimeo.com', url: 'https://vimeo.com', category: 'Video', rank: 74 },
    { name: 'Fandom', domain: 'fandom.com', url: 'https://fandom.com', category: 'Entertainment', rank: 75 },
    { name: 'Roblox', domain: 'roblox.com', url: 'https://roblox.com', category: 'Gaming', rank: 76 },
    { name: 'Coursera', domain: 'coursera.org', url: 'https://coursera.org', category: 'Education', rank: 77 },
    { name: 'edX', domain: 'edx.org', url: 'https://edx.org', category: 'Education', rank: 78 },
    { name: 'Khan Academy', domain: 'khanacademy.org', url: 'https://khanacademy.org', category: 'Education', rank: 79 },
    { name: 'Zillow', domain: 'zillow.com', url: 'https://zillow.com', category: 'Real Estate', rank: 80 },
    { name: 'Chase', domain: 'chase.com', url: 'https://chase.com', category: 'Finance', rank: 81 },
    { name: 'Bank of America', domain: 'bankofamerica.com', url: 'https://bankofamerica.com', category: 'Finance', rank: 82 },
    { name: 'Wells Fargo', domain: 'wellsfargo.com', url: 'https://wellsfargo.com', category: 'Finance', rank: 83 },
    { name: 'The Weather Channel', domain: 'weather.com', url: 'https://weather.com', category: 'Weather', rank: 84 },
    { name: 'UPS', domain: 'ups.com', url: 'https://ups.com', category: 'Logistics', rank: 85 },
    { name: 'FedEx', domain: 'fedex.com', url: 'https://fedex.com', category: 'Logistics', rank: 86 },
    { name: 'Craigslist', domain: 'craigslist.org', url: 'https://craigslist.org', category: 'Classifieds', rank: 87 },
    { name: 'Mozilla', domain: 'mozilla.org', url: 'https://mozilla.org', category: 'Technology', rank: 88 },
    { name: 'Evernote', domain: 'evernote.com', url: 'https://evernote.com', category: 'Productivity', rank: 89 },
    { name: 'Asana', domain: 'asana.com', url: 'https://asana.com', category: 'Productivity', rank: 90 },
    { name: 'Trello', domain: 'trello.com', url: 'https://trello.com', category: 'Productivity', rank: 91 },
    { name: 'Hulu', domain: 'hulu.com', url: 'https://hulu.com', category: 'Streaming', rank: 92 },
    { name: 'Disney+', domain: 'disneyplus.com', url: 'https://disneyplus.com', category: 'Streaming', rank: 93 },
    { name: 'HBO Max', domain: 'hbomax.com', url: 'https://hbomax.com', category: 'Streaming', rank: 94 },
    { name: 'Bloomberg', domain: 'bloomberg.com', url: 'https://bloomberg.com', category: 'Business', rank: 95 },
    { name: 'Reuters', domain: 'reuters.com', url: 'https://reuters.com', category: 'News', rank: 96 },
    { name: 'Associated Press', domain: 'apnews.com', url: 'https://apnews.com', category: 'News', rank: 97 },
    { name: 'Time', domain: 'time.com', url: 'https://time.com', category: 'News', rank: 98 },
    { name: 'Stripe', domain: 'stripe.com', url: 'https://stripe.com', category: 'Finance', rank: 99 },
    { name: 'Atlassian', domain: 'atlassian.com', url: 'https://atlassian.com', category: 'Software', rank: 100 }
];
