
export const topSites = [
    { name: 'Google', domain: 'google.com', url: 'https://google.com', category: 'Search Engine' },
    { name: 'YouTube', domain: 'youtube.com', url: 'https://youtube.com', category: 'Video' },
    { name: 'Facebook', domain: 'facebook.com', url: 'https://facebook.com', category: 'Social Media' },
    { name: 'X (Twitter)', domain: 'x.com', url: 'https://x.com', category: 'Social Media' },
    { name: 'Instagram', domain: 'instagram.com', url: 'https://instagram.com', category: 'Social Media' },
    { name: 'Wikipedia', domain: 'wikipedia.org', url: 'https://wikipedia.org', category: 'Reference' },
    { name: 'Amazon', domain: 'amazon.com', url: 'https://amazon.com', category: 'E-commerce' },
    { name: 'Netflix', domain: 'netflix.com', url: 'https://netflix.com', category: 'Streaming' },
    { name: 'Reddit', domain: 'reddit.com', url: 'https://reddit.com', category: 'Social Media' },
    { name: 'LinkedIn', domain: 'linkedin.com', url: 'https://linkedin.com', category: 'Professional' },
    { name: 'The New York Times', domain: 'nytimes.com', url: 'https://www.nytimes.com', category: 'News' },
    { name: 'BBC', domain: 'bbc.com', url: 'https://www.bbc.com', category: 'News' },
    { name: 'Microsoft', domain: 'microsoft.com', url: 'https://microsoft.com', category: 'Technology' },
    { name: 'Apple', domain: 'apple.com', url: 'https://apple.com', category: 'Technology' },
    { name: 'GitHub', domain: 'github.com', url: 'https://github.com', category: 'Developer' },
    { name: 'Stack Overflow', domain: 'stackoverflow.com', url: 'https://stackoverflow.com', category: 'Developer' },
    { name: 'Vercel', domain: 'vercel.com', url: 'https://vercel.com', category: 'Developer' },
    { name: 'Figma', domain: 'figma.com', url: 'https://figma.com', category: 'Design' },
    { name: 'Canva', domain: 'canva.com', url: 'https://canva.com', category: 'Design' },
    { name: 'Spotify', domain: 'spotify.com', url: 'https://spotify.com', category: 'Music' },
    { name: 'TikTok', domain: 'tiktok.com', url: 'https://tiktok.com', category: 'Social Media' },
    { name: 'Pinterest', domain: 'pinterest.com', url: 'https://pinterest.com', category: 'Social Media' },
    { name: 'eBay', domain: 'ebay.com', url: 'https://ebay.com', category: 'E-commerce' },
    { name: 'Walmart', domain: 'walmart.com', url: 'https://walmart.com', category: 'E-commerce' },
    { name: 'Target', domain: 'target.com', url: 'https://target.com', category: 'E-commerce' },
    { name: 'The Guardian', domain: 'theguardian.com', url: 'https://theguardian.com/international', category: 'News' },
    { name: 'CNN', domain: 'cnn.com', url: 'https://cnn.com', category: 'News' },
    { name: 'Forbes', domain: 'forbes.com', url: 'https://forbes.com', category: 'Business' },
    { name: 'ESPN', domain: 'espn.com', url: 'https://espn.com', category: 'Sports' },
    { name: 'IMDb', domain: 'imdb.com', url: 'https://imdb.com', category: 'Entertainment' },
    { name: 'Twitch', domain: 'twitch.tv', url: 'https://twitch.tv', category: 'Streaming' },
    { name: 'Adobe', domain: 'adobe.com', url: 'https://adobe.com', category: 'Software' },
    { name: 'Salesforce', domain: 'salesforce.com', url: 'https://salesforce.com', category: 'Business' },
    { name: 'PayPal', domain: 'paypal.com', url: 'https://paypal.com', category: 'Finance' },
    { name: 'Dropbox', domain: 'dropbox.com', url: 'https://dropbox.com', category: 'Cloud Storage' },
    { name: 'Slack', domain: 'slack.com', url: 'https://slack.com', category: 'Productivity' },
    { name: 'Zoom', domain: 'zoom.us', url: 'https://zoom.us', category: 'Productivity' },
    { name: 'Quora', domain: 'quora.com', url: 'https://quora.com', category: 'Q&A' },
    { name: 'Medium', domain: 'medium.com', url: 'https://medium.com', category: 'Blogging' },
    { name: 'Booking.com', domain: 'booking.com', url: 'https://booking.com', category: 'Travel' },
    { name: 'Airbnb', domain: 'airbnb.com', url: 'https://airbnb.com', category: 'Travel' },
    { name: 'Uber', domain: 'uber.com', url: 'https://uber.com', category: 'Transportation' },
    { name: 'Lyft', domain: 'lyft.com', url: 'https://lyft.com', category: 'Transportation' },
    { name: 'DoorDash', domain: 'doordash.com', url: 'https://doordash.com', category: 'Food Delivery' },
    { name: 'Etsy', domain: 'etsy.com', url: 'https://etsy.com', category: 'E-commerce' },
    { name: 'Shopify', domain: 'shopify.com', url: 'https://shopify.com', category: 'E-commerce' },
    { name: 'WordPress.org', domain: 'wordpress.org', url: 'https://wordpress.org', category: 'CMS' },
    { name: 'Wix', domain: 'wix.com', url: 'https://wix.com', category: 'Website Builder' },
    { name: 'Squarespace', domain: 'squarespace.com', url: 'https://squarespace.com', category: 'Website Builder' },
    { name: 'The Verge', domain: 'theverge.com', url: 'https://theverge.com', category: 'Tech News' },
    { name: 'TechCrunch', domain: 'techcrunch.com', url: 'https://techcrunch.com', category: 'Tech News' },
    { name: 'Hacker News', domain: 'ycombinator.com', url: 'https://news.ycombinator.com', category: 'Tech News' },
    { name: 'National Geographic', domain: 'nationalgeographic.com', url: 'https://nationalgeographic.com', category: 'Education' },
    { name: 'NASA', domain: 'nasa.gov', url: 'https://nasa.gov', category: 'Science' },
    { name: 'WebMD', domain: 'webmd.com', url: 'https://webmd.com', category: 'Health' },
    { name: 'Healthline', domain: 'healthline.com', url: 'https://healthline.com', category: 'Health' },
    { name: 'Allrecipes', domain: 'allrecipes.com', url: 'https://allrecipes.com', category: 'Food' },
    { name: 'Food Network', domain: 'foodnetwork.com', url: 'https://foodnetwork.com', category: 'Food' },
    { name: 'IGN', domain: 'ign.com', url: 'https://ign.com', category: 'Gaming' },
    { name: 'GameSpot', domain: 'gamespot.com', url: 'https://gamespot.com', category: 'Gaming' },
    { name: 'Rotten Tomatoes', domain: 'rottentomatoes.com', url: 'https://rottentomatoes.com', category: 'Entertainment' },
    { name: 'SoundCloud', domain: 'soundcloud.com', url: 'https://soundcloud.com', category: 'Music' },
    { name: 'Bandcamp', domain: 'bandcamp.com', url: 'https://bandcamp.com', category: 'Music' },
    { name: 'DeviantArt', domain: 'deviantart.com', url: 'https://deviantart.com', category: 'Art' },
    { name: 'Behance', domain: 'behance.net', url: 'https://behance.net', category: 'Design' },
    { name: 'Dribbble', domain: 'dribbble.com', url: 'https://dribbble.com', category: 'Design' },
    { name: 'Alibaba', domain: 'alibaba.com', url: 'https://alibaba.com', category: 'E-commerce' },
    { name: 'Tencent', domain: 'tencent.com', url: 'https://tencent.com', category: 'Technology' },
    { name: 'Baidu', domain: 'baidu.com', url: 'https://baidu.com', category: 'Search Engine' },
    { name: 'Yahoo', domain: 'yahoo.com', url: 'https://yahoo.com', category: 'Portal' },
    { name: 'WhatsApp', domain: 'whatsapp.com', url: 'https://whatsapp.com', category: 'Social Media' },
    { name: 'Telegram', domain: 'telegram.org', url: 'https://telegram.org', category: 'Social Media' },
    { name: 'Discord', domain: 'discord.com', url: 'https://discord.com', category: 'Social Media' },
    { name: 'Vimeo', domain: 'vimeo.com', url: 'https://vimeo.com', category: 'Video' },
    { name: 'Fandom', domain: 'fandom.com', url: 'https://fandom.com', category: 'Entertainment' },
    { name: 'Roblox', domain: 'roblox.com', url: 'https://roblox.com', category: 'Gaming' },
    { name: 'Coursera', domain: 'coursera.org', url: 'https://coursera.org', category: 'Education' },
    { name: 'edX', domain: 'edx.org', url: 'https://edx.org', category: 'Education' },
    { name: 'Khan Academy', domain: 'khanacademy.org', url: 'https://khanacademy.org', category: 'Education' },
    { name: 'Zillow', domain: 'zillow.com', url: 'https://zillow.com', category: 'Real Estate' },
    { name: 'Chase', domain: 'chase.com', url: 'https://chase.com', category: 'Finance' },
    { name: 'Bank of America', domain: 'bankofamerica.com', url: 'https://bankofamerica.com', category: 'Finance' },
    { name: 'Wells Fargo', domain: 'wellsfargo.com', url: 'https://wellsfargo.com', category: 'Finance' },
    { name: 'The Weather Channel', domain: 'weather.com', url: 'https://weather.com', category: 'Weather' },
    { name: 'UPS', domain: 'ups.com', url: 'https://ups.com', category: 'Logistics' },
    { name: 'FedEx', domain: 'fedex.com', url: 'https://fedex.com', category: 'Logistics' },
    { name: 'Craigslist', domain: 'craigslist.org', url: 'https://craigslist.org', category: 'Classifieds' },
    { name: 'Mozilla', domain: 'mozilla.org', url: 'https://mozilla.org', category: 'Technology' },
    { name: 'Evernote', domain: 'evernote.com', url: 'https://evernote.com', category: 'Productivity' },
    { name: 'Asana', domain: 'asana.com', url: 'https://asana.com', category: 'Productivity' },
    { name: 'Trello', domain: 'trello.com', url: 'https://trello.com', category: 'Productivity' },
    { name: 'Hulu', domain: 'hulu.com', url: 'https://hulu.com', category: 'Streaming' },
    { name: 'Disney+', domain: 'disneyplus.com', url: 'https://disneyplus.com', category: 'Streaming' },
    { name: 'HBO Max', domain: 'hbomax.com', url: 'https://hbomax.com', category: 'Streaming' },
    { name: 'Bloomberg', domain: 'bloomberg.com', url: 'https://bloomberg.com', category: 'Business' },
    { name: 'Reuters', domain: 'reuters.com', url: 'https://reuters.com', category: 'News' },
    { name: 'Associated Press', domain: 'apnews.com', url: 'https://apnews.com', category: 'News' },
    { name: 'Time', domain: 'time.com', url: 'https://time.com', category: 'News' },
    { name: 'Stripe', domain: 'stripe.com', url: 'https://stripe.com', category: 'Finance' },
    { name: 'Atlassian', domain: 'atlassian.com', url: 'https://atlassian.com', category: 'Software' }
];
