
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Home, Shield } from "lucide-react";
import Link from "next/link";

export default function PrivacyPage() {
  return (
    <div className="container mx-auto px-4 py-8 max-w-4xl space-y-8">
      <div className="flex flex-wrap justify-between items-center gap-4">
        <h1 className="text-3xl md:text-4xl font-bold flex items-center gap-3">
          <Shield className="h-8 w-8 text-primary" />
          Privacy Policy
        </h1>
        <Button asChild variant="outline">
          <Link href="/">
            <Home className="mr-2 h-4 w-4" />
            Back to Home
          </Link>
        </Button>
      </div>

      <Card className="glass-card">
        <CardHeader>
          <CardTitle>Last Updated: [Date]</CardTitle>
        </CardHeader>
        <CardContent className="prose prose-sm sm:prose-base lg:prose-lg dark:prose-invert max-w-none text-muted-foreground">
          <p>
            This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service. This is placeholder text. It is crucial to replace this content with a legally compliant document drafted by a qualified legal professional.
          </p>

          <h2>1. Interpretation and Definitions</h2>
          <p>
            <strong>Personal Data</strong> is any information that relates to an identified or identifiable individual. For the purposes of the Nigeria Data Protection Regulation (NDPR), Personal Data means any information relating to an identified or identifiable natural person.
          </p>
          <p>
            <strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).
          </p>

          <h2>2. Collecting and Using Your Personal Data</h2>
          <h3>Types of Data Collected</h3>
          <p>
            <strong>Personal Data:</strong> While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to: Email address, First name and last name, and Usage Data.
          </p>
          <p>
            <strong>Usage Data:</strong> Usage Data is collected automatically when using the Service. This may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.
          </p>

          <h2>3. Use of Your Personal Data</h2>
          <p>The Company may use Personal Data for the following purposes:</p>
          <ul>
            <li>To provide and maintain our Service, including to monitor the usage of our Service.</li>
            <li>To manage Your Account: to manage Your registration as a user of the Service.</li>
            <li>For the performance of a contract: the development, compliance and undertaking of the purchase contract for the products, items or services You have purchased or of any other contract with Us through the Service.</li>
            <li>To contact You: To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication.</li>
          </ul>

          <h2>4. Retention of Your Personal Data</h2>
          <p>
            The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.
          </p>
          
          <h2>5. Your Data Protection Rights under the Nigeria Data Protection Regulation (NDPR)</h2>
          <p>
             In accordance with the NDPR, you have certain data protection rights. WebIntel is committed to enabling you to exercise these rights. These include the right to access, update, or delete your information; the right of rectification; the right to object; the right of restriction; and the right to data portability.
          </p>

          <h2>6. International Data Transfers</h2>
          <p>
            Your information, including Personal Data, is processed at the Company's operating offices and in any other places where the parties involved in the processing are located. It means that this information may be transferred to — and maintained on — computers located outside of Your state, province, country or other governmental jurisdiction where the data protection laws may differ from those from Your jurisdiction.
          </p>

          <h2>7. Security of Your Personal Data</h2>
          <p>
            The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.
          </p>

          <p className="font-bold text-destructive">
            This document is a template and not legal advice. Consult with a legal professional to ensure your Privacy Policy is compliant with all applicable laws, including the NDPR, GDPR, and other international regulations.
          </p>

        </CardContent>
      </Card>
    </div>
  );
}
